title: Municipal Broadband Coalition of America
email: info@mbcoa.org
description: >
  The advocacy group for municipal broadband.
url: "https://www.mbcoa.org"
social:
  links:
    - https://github.com/municipalbroadband
github_username: mbcoa
github_url: "https://github.com/municipalbroadband/mbcoa.org"

baseurl: ''
permalink: /blog/:year/:month/:title:output_ext

markdown: kramdown

paginate: 10
paginate_path: /blog/p:num/

timezone: America/Los_Angeles

exclude:
- CODE_OF_CONDUCT.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from

webrick:
  headers:
    Content-Security-Policy: >-
      default-src 'none';
      child-src https:;
      img-src 'self' https://www.google-analytics.com data:;
      font-src 'self';
      script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com;
      style-src 'self';
      object-src 'none';
      frame-src https:;
      frame-ancestors 'none'
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: strict-origin-when-cross-origin
